// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { persistentSessionStorage } from './persistentSessionStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Sessão eterna: salva no localStorage e só o logout explícito encerra.
    // Não usar o broker de preview do Lovable, ele apaga o token ao recarregar.
    storage: persistentSessionStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});